# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config/connections/analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'config/connections/analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!config/connections/analyzer.proto\x12\x04user\"8\n\x08UserData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x62pm\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"-\n\x0eInsertResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2E\n\x0bUserService\x12\x36\n\x0eInsertUserData\x12\x0e.user.UserData\x1a\x14.user.InsertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.connections.analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDATA']._serialized_start=43
  _globals['_USERDATA']._serialized_end=99
  _globals['_INSERTRESPONSE']._serialized_start=101
  _globals['_INSERTRESPONSE']._serialized_end=146
  _globals['_USERSERVICE']._serialized_start=148
  _globals['_USERSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
